@WebAthenPs_HostAddress = http://localhost:5082

GET {{WebAthenPs_HostAddress}}/weatherforecast/
Accept: application/json

###

POST {{WebAthenPs_HostAddress}}/api/users/login
Content-Type: application/json